// Auto-generated by fetch-cloudinary-images.js
// Run: node fetch-cloudinary-images.js to update
// Last updated: 2025-12-14T20:09:10.161Z

// Assign to window.images for global access
window.images = {
  "dreams": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-35",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-35",
      "alt": "dream-35",
      "publicId": "dream-35",
      "displayName": "dream-35"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-36",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-36",
      "alt": "dream-36",
      "publicId": "dream-36",
      "displayName": "dream-36"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-34",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-34",
      "alt": "dream-34",
      "publicId": "dream-34",
      "displayName": "dream-34"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-33",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-33",
      "alt": "dream-33",
      "publicId": "dream-33",
      "displayName": "dream-33"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-32",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-32",
      "alt": "dream-32",
      "publicId": "dream-32",
      "displayName": "dream-32"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-31",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-31",
      "alt": "dream-31",
      "publicId": "dream-31",
      "displayName": "dream-31"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-30",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-30",
      "alt": "dream-30",
      "publicId": "dream-30",
      "displayName": "dream-30"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-25",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-25",
      "alt": "dream-25",
      "publicId": "dream-25",
      "displayName": "dream-25"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-23",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-23",
      "alt": "dream-23",
      "publicId": "dream-23",
      "displayName": "dream-23"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-27",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-27",
      "alt": "dream-27",
      "publicId": "dream-27",
      "displayName": "dream-27"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-28",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-28",
      "alt": "dream-28",
      "publicId": "dream-28",
      "displayName": "dream-28"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-26",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-26",
      "alt": "dream-26",
      "publicId": "dream-26",
      "displayName": "dream-26"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-24",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-24",
      "alt": "dream-24",
      "publicId": "dream-24",
      "displayName": "dream-24"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-15",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-15",
      "alt": "dream-15",
      "publicId": "dream-15",
      "displayName": "dream-15"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-21",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-21",
      "alt": "dream-21",
      "publicId": "dream-21",
      "displayName": "dream-21"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-22",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-22",
      "alt": "dream-22",
      "publicId": "dream-22",
      "displayName": "dream-22"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-20",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-20",
      "alt": "dream-20",
      "publicId": "dream-20",
      "displayName": "dream-20"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-19",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-19",
      "alt": "dream-19",
      "publicId": "dream-19",
      "displayName": "dream-19"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-13",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-13",
      "alt": "dream-13",
      "publicId": "dream-13",
      "displayName": "dream-13"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-17",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-17",
      "alt": "dream-17",
      "publicId": "dream-17",
      "displayName": "dream-17"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-16",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-16",
      "alt": "dream-16",
      "publicId": "dream-16",
      "displayName": "dream-16"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-18",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-18",
      "alt": "dream-18",
      "publicId": "dream-18",
      "displayName": "dream-18"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-14",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-14",
      "alt": "dream-14",
      "publicId": "dream-14",
      "displayName": "dream-14"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-11",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-11",
      "alt": "dream-11",
      "publicId": "dream-11",
      "displayName": "dream-11"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-10",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-10",
      "alt": "dream-10",
      "publicId": "dream-10",
      "displayName": "dream-10"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-6",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-6",
      "alt": "dream-6",
      "publicId": "dream-6",
      "displayName": "dream-6"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-12",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-12",
      "alt": "dream-12",
      "publicId": "dream-12",
      "displayName": "dream-12"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-7",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-7",
      "alt": "dream-7",
      "publicId": "dream-7",
      "displayName": "dream-7"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-4",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-4",
      "alt": "dream-4",
      "publicId": "dream-4",
      "displayName": "dream-4"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-8",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-8",
      "alt": "dream-8",
      "publicId": "dream-8",
      "displayName": "dream-8"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-9",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-9",
      "alt": "dream-9",
      "publicId": "dream-9",
      "displayName": "dream-9"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-2",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-2",
      "alt": "dream-2",
      "publicId": "dream-2",
      "displayName": "dream-2"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-5",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-5",
      "alt": "dream-5",
      "publicId": "dream-5",
      "displayName": "dream-5"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-3",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-3",
      "alt": "dream-3",
      "publicId": "dream-3",
      "displayName": "dream-3"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream",
      "alt": "dream",
      "publicId": "dream",
      "displayName": "dream"
    }
  ],
  "mandalas": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/v1/mandala/ynpusb1mocrwlmttuxax",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/v1/mandala/ynpusb1mocrwlmttuxax",
      "alt": "Earthly_Resonance",
      "publicId": "mandala/ynpusb1mocrwlmttuxax",
      "displayName": "Earthly_Resonance"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/v1/mandala/rvy275tatpccyoa5lhon",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/v1/mandala/rvy275tatpccyoa5lhon",
      "alt": "Watcher",
      "publicId": "mandala/rvy275tatpccyoa5lhon",
      "displayName": "Watcher"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/v1/mandala/r2chba1aje7bzjj0gfr7",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/v1/mandala/r2chba1aje7bzjj0gfr7",
      "alt": "Encoded",
      "publicId": "mandala/r2chba1aje7bzjj0gfr7",
      "displayName": "Encoded"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Wild_Elements_bu9ahz",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Wild_Elements_bu9ahz",
      "alt": "Wild_Elements_bu9ahz",
      "publicId": "Wild_Elements_bu9ahz",
      "displayName": "Wild_Elements_bu9ahz"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Viborita_dm3gpy",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Viborita_dm3gpy",
      "alt": "Viborita_dm3gpy",
      "publicId": "Viborita_dm3gpy",
      "displayName": "Viborita_dm3gpy"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Two_Dimension_ijfsxu",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Two_Dimension_ijfsxu",
      "alt": "Two_Dimension_ijfsxu",
      "publicId": "Two_Dimension_ijfsxu",
      "displayName": "Two_Dimension_ijfsxu"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Universal_elyxrj",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Universal_elyxrj",
      "alt": "Universal_elyxrj",
      "publicId": "Universal_elyxrj",
      "displayName": "Universal_elyxrj"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Swift_xgqim4",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Swift_xgqim4",
      "alt": "Swift_xgqim4",
      "publicId": "Swift_xgqim4",
      "displayName": "Swift_xgqim4"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Sun_Vitamin_wxmmea",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Sun_Vitamin_wxmmea",
      "alt": "Sun_Vitamin_wxmmea",
      "publicId": "Sun_Vitamin_wxmmea",
      "displayName": "Sun_Vitamin_wxmmea"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Star_Resonance_uzlztb",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Star_Resonance_uzlztb",
      "alt": "Star_Resonance_uzlztb",
      "publicId": "Star_Resonance_uzlztb",
      "displayName": "Star_Resonance_uzlztb"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Star_Gear_ytyz6i",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Star_Gear_ytyz6i",
      "alt": "Star_Gear_ytyz6i",
      "publicId": "Star_Gear_ytyz6i",
      "displayName": "Star_Gear_ytyz6i"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Snakey__r4vrww",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Snakey__r4vrww",
      "alt": "Snakey__r4vrww",
      "publicId": "Snakey__r4vrww",
      "displayName": "Snakey__r4vrww"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Petals_In_Water_tkcegs",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Petals_In_Water_tkcegs",
      "alt": "Petals_In_Water_tkcegs",
      "publicId": "Petals_In_Water_tkcegs",
      "displayName": "Petals_In_Water_tkcegs"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Row_hsmskm",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Row_hsmskm",
      "alt": "Row_hsmskm",
      "publicId": "Row_hsmskm",
      "displayName": "Row_hsmskm"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/North_Star_tbgypz",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/North_Star_tbgypz",
      "alt": "North_Star_tbgypz",
      "publicId": "North_Star_tbgypz",
      "displayName": "North_Star_tbgypz"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Nativo_sk21to",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Nativo_sk21to",
      "alt": "Nativo_sk21to",
      "publicId": "Nativo_sk21to",
      "displayName": "Nativo_sk21to"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Money_On_My_Mind_wp2kkl",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Money_On_My_Mind_wp2kkl",
      "alt": "Money_On_My_Mind_wp2kkl",
      "publicId": "Money_On_My_Mind_wp2kkl",
      "displayName": "Money_On_My_Mind_wp2kkl"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Napkin_Idea_be23ow",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Napkin_Idea_be23ow",
      "alt": "Napkin_Idea_be23ow",
      "publicId": "Napkin_Idea_be23ow",
      "displayName": "Napkin_Idea_be23ow"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Knotted_vr7moa",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Knotted_vr7moa",
      "alt": "Knotted_vr7moa",
      "publicId": "Knotted_vr7moa",
      "displayName": "Knotted_vr7moa"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Illegible_nrfd2h",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Illegible_nrfd2h",
      "alt": "Illegible_nrfd2h",
      "publicId": "Illegible_nrfd2h",
      "displayName": "Illegible_nrfd2h"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Heritage_jmahwf",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Heritage_jmahwf",
      "alt": "Heritage_jmahwf",
      "publicId": "Heritage_jmahwf",
      "displayName": "Heritage_jmahwf"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Growth_zo2ibh",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Growth_zo2ibh",
      "alt": "Growth_zo2ibh",
      "publicId": "Growth_zo2ibh",
      "displayName": "Growth_zo2ibh"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Fluff_eye9ng",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Fluff_eye9ng",
      "alt": "Fluff_eye9ng",
      "publicId": "Fluff_eye9ng",
      "displayName": "Fluff_eye9ng"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Golden_Architecture_qjzu7v",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Golden_Architecture_qjzu7v",
      "alt": "Golden_Architecture_qjzu7v",
      "publicId": "Golden_Architecture_qjzu7v",
      "displayName": "Golden_Architecture_qjzu7v"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Core_t5tzmo",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Core_t5tzmo",
      "alt": "Core_t5tzmo",
      "publicId": "Core_t5tzmo",
      "displayName": "Core_t5tzmo"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Chocolate_jj6w4k",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Chocolate_jj6w4k",
      "alt": "Chocolate_jj6w4k",
      "publicId": "Chocolate_jj6w4k",
      "displayName": "Chocolate_jj6w4k"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Burst_zasz9j",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Burst_zasz9j",
      "alt": "Burst_zasz9j",
      "publicId": "Burst_zasz9j",
      "displayName": "Burst_zasz9j"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Blueprint_gvwd2a",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Blueprint_gvwd2a",
      "alt": "Blueprint_gvwd2a",
      "publicId": "Blueprint_gvwd2a",
      "displayName": "Blueprint_gvwd2a"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Bloom_zpqxov",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Bloom_zpqxov",
      "alt": "Bloom_zpqxov",
      "publicId": "Bloom_zpqxov",
      "displayName": "Bloom_zpqxov"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Architected_vben9d",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Architected_vben9d",
      "alt": "Architected_vben9d",
      "publicId": "Architected_vben9d",
      "displayName": "Architected_vben9d"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Abrupt_w9xijs",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Abrupt_w9xijs",
      "alt": "Abrupt_w9xijs",
      "publicId": "Abrupt_w9xijs",
      "displayName": "Abrupt_w9xijs"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Ancient_Memory_d0qmsp",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Ancient_Memory_d0qmsp",
      "alt": "Ancient_Memory_d0qmsp",
      "publicId": "Ancient_Memory_d0qmsp",
      "displayName": "Ancient_Memory_d0qmsp"
    }
  ],
  "voices": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Remember_h28gcj",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Remember_h28gcj",
      "alt": "Remember_h28gcj",
      "publicId": "Remember_h28gcj",
      "displayName": "Remember_h28gcj"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Calm_s9ufmr",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Calm_s9ufmr",
      "alt": "Calm_s9ufmr",
      "publicId": "Calm_s9ufmr",
      "displayName": "Calm_s9ufmr"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Paranoia__xiyzky",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Paranoia__xiyzky",
      "alt": "Paranoia__xiyzky",
      "publicId": "Paranoia__xiyzky",
      "displayName": "Paranoia__xiyzky"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Focus_t9tcrx",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Focus_t9tcrx",
      "alt": "Focus_t9tcrx",
      "publicId": "Focus_t9tcrx",
      "displayName": "Focus_t9tcrx"
    }
  ],
  "animals": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Rattlesnake_m4lord",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Rattlesnake_m4lord",
      "alt": "Rattlesnake_m4lord",
      "publicId": "Rattlesnake_m4lord",
      "displayName": "Rattlesnake_m4lord"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Owl_alam79",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Owl_alam79",
      "alt": "Owl_alam79",
      "publicId": "Owl_alam79",
      "displayName": "Owl_alam79"
    }
  ],
  "songart": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/What_Happens_Now_zcagjj",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/What_Happens_Now_zcagjj",
      "alt": "What_Happens_Now_zcagjj",
      "publicId": "What_Happens_Now_zcagjj",
      "displayName": "What_Happens_Now_zcagjj"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Wander_h3lh04",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Wander_h3lh04",
      "alt": "Wander_h3lh04",
      "publicId": "Wander_h3lh04",
      "displayName": "Wander_h3lh04"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Standalone__ojrbpd",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Standalone__ojrbpd",
      "alt": "Standalone__ojrbpd",
      "publicId": "Standalone__ojrbpd",
      "displayName": "Standalone__ojrbpd"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Sol_zesbgq",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Sol_zesbgq",
      "alt": "Sol_zesbgq",
      "publicId": "Sol_zesbgq",
      "displayName": "Sol_zesbgq"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Pensive_winhvx",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Pensive_winhvx",
      "alt": "Pensive_winhvx",
      "publicId": "Pensive_winhvx",
      "displayName": "Pensive_winhvx"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Obscuro_nuw6vq",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Obscuro_nuw6vq",
      "alt": "Obscuro_nuw6vq",
      "publicId": "Obscuro_nuw6vq",
      "displayName": "Obscuro_nuw6vq"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/La_Luna_zpuyld",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/La_Luna_zpuyld",
      "alt": "La_Luna_zpuyld",
      "publicId": "La_Luna_zpuyld",
      "displayName": "La_Luna_zpuyld"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Latebloomer_EP_ck7tcm",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Latebloomer_EP_ck7tcm",
      "alt": "Latebloomer_EP_ck7tcm",
      "publicId": "Latebloomer_EP_ck7tcm",
      "displayName": "Latebloomer_EP_ck7tcm"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/El_Diablito_poz9xb",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/El_Diablito_poz9xb",
      "alt": "El_Diablito_poz9xb",
      "publicId": "El_Diablito_poz9xb",
      "displayName": "El_Diablito_poz9xb"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/El_Cotorro_az7mbb",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/El_Cotorro_az7mbb",
      "alt": "El_Cotorro_az7mbb",
      "publicId": "El_Cotorro_az7mbb",
      "displayName": "El_Cotorro_az7mbb"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Quien_Fue_xwqysd",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Quien_Fue_xwqysd",
      "alt": "Quien_Fue_xwqysd",
      "publicId": "Quien_Fue_xwqysd",
      "displayName": "Quien_Fue_xwqysd"
    }
  ]
};
