// Auto-generated by fetch-cloudinary-images.js
// Run: node fetch-cloudinary-images.js to update
// Last updated: 2025-12-13T18:31:07.487Z

// Assign to window.images for global access
window.images = {
  "dreams": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-35",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-35",
      "alt": "dream 35"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-36",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-36",
      "alt": "dream 36"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-34",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-34",
      "alt": "dream 34"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-33",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-33",
      "alt": "dream 33"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-32",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-32",
      "alt": "dream 32"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-31",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-31",
      "alt": "dream 31"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-30",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-30",
      "alt": "dream 30"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-25",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-25",
      "alt": "dream 25"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-23",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-23",
      "alt": "dream 23"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-27",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-27",
      "alt": "dream 27"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-28",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-28",
      "alt": "dream 28"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-26",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-26",
      "alt": "dream 26"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-24",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-24",
      "alt": "dream 24"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-15",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-15",
      "alt": "dream 15"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-21",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-21",
      "alt": "dream 21"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-22",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-22",
      "alt": "dream 22"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-20",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-20",
      "alt": "dream 20"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-19",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-19",
      "alt": "dream 19"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-13",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-13",
      "alt": "dream 13"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-17",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-17",
      "alt": "dream 17"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-16",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-16",
      "alt": "dream 16"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-18",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-18",
      "alt": "dream 18"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-14",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-14",
      "alt": "dream 14"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-11",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-11",
      "alt": "dream 11"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-10",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-10",
      "alt": "dream 10"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-6",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-6",
      "alt": "dream 6"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-12",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-12",
      "alt": "dream 12"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-7",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-7",
      "alt": "dream 7"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-4",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-4",
      "alt": "dream 4"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-8",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-8",
      "alt": "dream 8"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-9",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-9",
      "alt": "dream 9"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-2",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-2",
      "alt": "dream 2"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-5",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-5",
      "alt": "dream 5"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream-3",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream-3",
      "alt": "dream 3"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/dream",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/dream",
      "alt": "dream"
    }
  ],
  "mandalas": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/v1/mandala/ynpusb1mocrwlmttuxax",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/v1/mandala/ynpusb1mocrwlmttuxax",
      "alt": "ynpusb1mocrwlmttuxax"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/v1/mandala/rvy275tatpccyoa5lhon",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/v1/mandala/rvy275tatpccyoa5lhon",
      "alt": "rvy275tatpccyoa5lhon"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/v1/mandala/r2chba1aje7bzjj0gfr7",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/v1/mandala/r2chba1aje7bzjj0gfr7",
      "alt": "r2chba1aje7bzjj0gfr7"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Wild_Elements_bu9ahz",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Wild_Elements_bu9ahz",
      "alt": "Wild Elements bu9ahz"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Viborita_dm3gpy",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Viborita_dm3gpy",
      "alt": "Viborita dm3gpy"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Two_Dimension_ijfsxu",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Two_Dimension_ijfsxu",
      "alt": "Two Dimension ijfsxu"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Universal_elyxrj",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Universal_elyxrj",
      "alt": "Universal elyxrj"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Swift_xgqim4",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Swift_xgqim4",
      "alt": "Swift xgqim4"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Sun_Vitamin_wxmmea",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Sun_Vitamin_wxmmea",
      "alt": "Sun Vitamin wxmmea"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Star_Resonance_uzlztb",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Star_Resonance_uzlztb",
      "alt": "Star Resonance uzlztb"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Star_Gear_ytyz6i",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Star_Gear_ytyz6i",
      "alt": "Star Gear ytyz6i"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Snakey__r4vrww",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Snakey__r4vrww",
      "alt": "Snakey  r4vrww"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Petals_In_Water_tkcegs",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Petals_In_Water_tkcegs",
      "alt": "Petals In Water tkcegs"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Row_hsmskm",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Row_hsmskm",
      "alt": "Row hsmskm"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/North_Star_tbgypz",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/North_Star_tbgypz",
      "alt": "North Star tbgypz"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Nativo_sk21to",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Nativo_sk21to",
      "alt": "Nativo sk21to"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Money_On_My_Mind_wp2kkl",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Money_On_My_Mind_wp2kkl",
      "alt": "Money On My Mind wp2kkl"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Napkin_Idea_be23ow",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Napkin_Idea_be23ow",
      "alt": "Napkin Idea be23ow"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Knotted_vr7moa",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Knotted_vr7moa",
      "alt": "Knotted vr7moa"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Illegible_nrfd2h",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Illegible_nrfd2h",
      "alt": "Illegible nrfd2h"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Heritage_jmahwf",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Heritage_jmahwf",
      "alt": "Heritage jmahwf"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Growth_zo2ibh",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Growth_zo2ibh",
      "alt": "Growth zo2ibh"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Fluff_eye9ng",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Fluff_eye9ng",
      "alt": "Fluff eye9ng"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Golden_Architecture_qjzu7v",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Golden_Architecture_qjzu7v",
      "alt": "Golden Architecture qjzu7v"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Core_t5tzmo",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Core_t5tzmo",
      "alt": "Core t5tzmo"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Chocolate_jj6w4k",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Chocolate_jj6w4k",
      "alt": "Chocolate jj6w4k"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Burst_zasz9j",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Burst_zasz9j",
      "alt": "Burst zasz9j"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Blueprint_gvwd2a",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Blueprint_gvwd2a",
      "alt": "Blueprint gvwd2a"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Bloom_zpqxov",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Bloom_zpqxov",
      "alt": "Bloom zpqxov"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Architected_vben9d",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Architected_vben9d",
      "alt": "Architected vben9d"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Abrupt_w9xijs",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Abrupt_w9xijs",
      "alt": "Abrupt w9xijs"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Ancient_Memory_d0qmsp",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Ancient_Memory_d0qmsp",
      "alt": "Ancient Memory d0qmsp"
    }
  ],
  "voices": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Remember_h28gcj",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Remember_h28gcj",
      "alt": "Remember h28gcj"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Calm_s9ufmr",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Calm_s9ufmr",
      "alt": "Calm s9ufmr"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Paranoia__xiyzky",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Paranoia__xiyzky",
      "alt": "Paranoia  xiyzky"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Focus_t9tcrx",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Focus_t9tcrx",
      "alt": "Focus t9tcrx"
    }
  ],
  "animals": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Rattlesnake_m4lord",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Rattlesnake_m4lord",
      "alt": "Rattlesnake m4lord"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Owl_alam79",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Owl_alam79",
      "alt": "Owl alam79"
    }
  ],
  "songart": [
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/What_Happens_Now_zcagjj",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/What_Happens_Now_zcagjj",
      "alt": "What Happens Now zcagjj"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Wander_h3lh04",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Wander_h3lh04",
      "alt": "Wander h3lh04"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Standalone__ojrbpd",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Standalone__ojrbpd",
      "alt": "Standalone  ojrbpd"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Sol_zesbgq",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Sol_zesbgq",
      "alt": "Sol zesbgq"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Pensive_winhvx",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Pensive_winhvx",
      "alt": "Pensive winhvx"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Obscuro_nuw6vq",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Obscuro_nuw6vq",
      "alt": "Obscuro nuw6vq"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/La_Luna_zpuyld",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/La_Luna_zpuyld",
      "alt": "La Luna zpuyld"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Latebloomer_EP_ck7tcm",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Latebloomer_EP_ck7tcm",
      "alt": "Latebloomer EP ck7tcm"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/El_Diablito_poz9xb",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/El_Diablito_poz9xb",
      "alt": "El Diablito poz9xb"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/El_Cotorro_az7mbb",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/El_Cotorro_az7mbb",
      "alt": "El Cotorro az7mbb"
    },
    {
      "url": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_800/Quien_Fue_xwqysd",
      "lightboxUrl": "http://res.cloudinary.com/dhjy8pfsa/image/upload/f_auto,q_auto/c_limit,w_2000/Quien_Fue_xwqysd",
      "alt": "Quien Fue xwqysd"
    }
  ]
};
